# Generated by Django 3.2.16 on 2023-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
