# Generated by Django 3.2.16 on 2023-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logout', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
